### ISSUE TITLE
Project category filter list is displayed incorrectly. Please test with chrome and edge

### ISSUE THREAD

**Issue by lightenup** [equinor/fusion-bmt#728]

**Comment by denektenina** [comment]
Andreas answered this on a call. Apparently it's on some browsers that we know of: On Chrome on Equinor windows-PC it opens upwards instead of downwards, and on Edge on Equinors windows-PC it's not possible to select in the dropdown. I suspect this has something to do with the fusion-component, and not our implementation. Will investigate further, we have the option to switch to another dropdown, but should then probably do it all places this dropdown is used (and we still have to verify that the new dropdown works).

Chrome and Edge looks good on my mac.

**Comment by ErlendHaa** [comment]
Officially, fusion doesn't support anything but Chrome - and as a result neither do we. I think maybe possibly that this information has not been properly communicated to the customer as they keep complaining about Edge

**Comment by lightenup** [comment]
Can't reproduce the same error on the office machine where it once occurred. Closing the issue
